<a href="https://colab.research.google.com/github/suchanya-pangam/670510749-229352-StatisticalLearning-or-Statistical-Learning-Labs./blob/main/Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
s = torch.tensor(2)
print(s)
print(s.shape)

tensor(2)
torch.Size([])


### Convert a tensor to scalar

In [ ]:
convert = s.item()
print(convert)

2


### Creating 2D tensor

In [ ]:
d = torch.tensor([[1, 2], [3, 4]])
print(d)

tensor([[1, 2],
        [3, 4]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
np_array = d.numpy()
print(np_array)
print(type(np_array))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


### Convert from numpy array to tensor

In [ ]:
numpy_array = np.array([[5, 6], [7, 8]])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)
print(type(tensor_from_numpy))

tensor([[5, 6],
        [7, 8]])
<class 'torch.Tensor'>


## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

## Basic operations

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Addition
print("Addition:", a + b)

# Subtraction
print("Subtraction:", b - a)

# Multiplication (element-wise)
print("Multiplication:", a * b)

# Division (element-wise)
print("Division:", b / a)

# Dot product (scalar product for 1D tensors)
print("Dot product (1D):")
c = torch.tensor([1, 2])
d = torch.tensor([3, 4])
print(torch.dot(c, d))

# Matrix multiplication (for 2D+ tensors, covered later as well)
print("\nMatrix multiplication (2D):")
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(m1, m2))

Addition: tensor([5, 7, 9])
Subtraction: tensor([3, 3, 3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([4.0000, 2.5000, 2.0000])
Dot product (1D):
tensor(11)

Matrix multiplication (2D):
tensor([[19, 22],
        [43, 50]])


### Matrix multiplication

In [ ]:
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
print("Matrix m1:", m1)
print("Matrix m2:", m2)
print("Result of m1 @ m2 (torch.matmul(m1, m2)):")
print(torch.matmul(m1, m2))

# You can also use the '@' operator for matrix multiplication
print("Result of m1 @ m2 (using @ operator):")
print(m1 @ m2)

Matrix m1: tensor([[1, 2],
        [3, 4]])
Matrix m2: tensor([[5, 6],
        [7, 8]])
Result of m1 @ m2 (torch.matmul(m1, m2)):
tensor([[19, 22],
        [43, 50]])
Result of m1 @ m2 (using @ operator):
tensor([[19, 22],
        [43, 50]])


### Matrix transpose

In [ ]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("Original matrix:")
print(matrix)
print("Shape:", matrix.shape)

# Transpose using .T attribute
matrix_t = matrix.T
print("\nTransposed matrix (using .T):")
print(matrix_t)
print("Shape:", matrix_t.shape)

# Transpose using .transpose() method
matrix_transpose_method = torch.transpose(matrix, 0, 1)
print("\nTransposed matrix (using .transpose()):")
print(matrix_transpose_method)
print("Shape:", matrix_transpose_method.shape)

Original matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

Transposed matrix (using .T):
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape: torch.Size([3, 2])

Transposed matrix (using .transpose()):
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape: torch.Size([3, 2])


## Creating a specific type of tensor

In [ ]:
# Create a tensor of zeros
zeros_tensor = torch.zeros(3, 4)
print("Zeros tensor:\n", zeros_tensor)

# Create a tensor of ones
ones_tensor = torch.ones(2, 3)
print("\nOnes tensor:\n", ones_tensor)

# Create a tensor with random values from a uniform distribution [0, 1)
random_uniform_tensor = torch.rand(2, 2)
print("\nRandom uniform tensor:\n", random_uniform_tensor)

# Create a tensor with random values from a standard normal distribution (mean=0, variance=1)
random_normal_tensor = torch.randn(1, 5)
print("\nRandom normal tensor:\n", random_normal_tensor)

# Create an identity matrix (2D square matrix with ones on the main diagonal and zeros elsewhere)
identity_matrix = torch.eye(3)
print("\nIdentity matrix:\n", identity_matrix)

Zeros tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random uniform tensor:
 tensor([[0.4092, 0.9555],
        [0.5116, 0.7960]])

Random normal tensor:
 tensor([[ 1.3558,  0.7159,  2.3194, -1.4063,  1.1458]])

Identity matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Tensor's shape

### Checking the shape of a tensor

In [ ]:
tensor_example = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Our example tensor:\n", tensor_example)
print("Shape of the tensor:", tensor_example.shape)

scalar_tensor = torch.tensor(10)
print("\nOur scalar tensor:\n", scalar_tensor)
print("Shape of the scalar tensor:", scalar_tensor.shape)

Our example tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Shape of the tensor: torch.Size([3, 4])

Our scalar tensor:
 tensor(10)
Shape of the scalar tensor: torch.Size([])


### Changing the shape of a tensor

In [ ]:
original_tensor = torch.arange(12)
print("Original tensor:", original_tensor)
print("Original shape:", original_tensor.shape)

# Using reshape
reshaped_tensor = original_tensor.reshape(3, 4)
print("\nReshaped tensor (3x4):\n", reshaped_tensor)
print("Reshaped shape:", reshaped_tensor.shape)

# Using view (only works if the new shape is compatible with the original tensor's memory layout)
viewed_tensor = original_tensor.view(4, 3)
print("\nViewed tensor (4x3):\n", viewed_tensor)
print("Viewed shape:", viewed_tensor.shape)

# Using -1 to infer a dimension
auto_reshaped_tensor = original_tensor.reshape(-1, 2)
print("\nAuto-reshaped tensor (inferred rows, 2 columns):\n", auto_reshaped_tensor)
print("Auto-reshaped shape:", auto_reshaped_tensor.shape)

# Adding a new dimension (unsqueeze)
new_dim_tensor = original_tensor.unsqueeze(0) # Add a dimension at position 0
print("\nTensor with new dimension (unsqueeze(0)):", new_dim_tensor)
print("Shape with new dimension:", new_dim_tensor.shape)

# Removing a dimension of size 1 (squeeze)
squeezed_tensor = new_dim_tensor.squeeze(0)
print("\nSqueezed tensor (remove dimension 0):\n", squeezed_tensor)
print("Squeezed shape:", squeezed_tensor.shape)

Original tensor: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])

Reshaped tensor (3x4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshaped shape: torch.Size([3, 4])

Viewed tensor (4x3):
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
Viewed shape: torch.Size([4, 3])

Auto-reshaped tensor (inferred rows, 2 columns):
 tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
Auto-reshaped shape: torch.Size([6, 2])

Tensor with new dimension (unsqueeze(0)): tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
Shape with new dimension: torch.Size([1, 12])

Squeezed tensor (remove dimension 0):
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Squeezed shape: torch.Size([12])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
# Define two example tensors
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

# Stacking tensors (creates a new dimension)
# Stack along a new dimension (dim=0 by default)
stacked_tensors_dim0 = torch.stack([tensor_a, tensor_b])
print("\nStacked tensors (dim=0):\n", stacked_tensors_dim0)
print("Shape of stacked tensors (dim=0):", stacked_tensors_dim0.shape)

# Stack along a new dimension (dim=1)
stacked_tensors_dim1 = torch.stack([tensor_a, tensor_b], dim=1)
print("\nStacked tensors (dim=1):\n", stacked_tensors_dim1)
print("Shape of stacked tensors (dim=1):", stacked_tensors_dim1.shape)

# Concatenating tensors (joins along an existing dimension)
# Concatenate along dimension 0 (rows)
concat_tensors_dim0 = torch.cat([tensor_a, tensor_b], dim=0)
print("\nConcatenated tensors (dim=0):\n", concat_tensors_dim0)
print("Shape of concatenated tensors (dim=0):", concat_tensors_dim0.shape)

# Concatenate along dimension 1 (columns)
concat_tensors_dim1 = torch.cat([tensor_a, tensor_b], dim=1)
print("\nConcatenated tensors (dim=1):\n", concat_tensors_dim1)
print("Shape of concatenated tensors (dim=1):", concat_tensors_dim1.shape)

Tensor A:
 tensor([[1, 2],
        [3, 4]])
Tensor B:
 tensor([[5, 6],
        [7, 8]])

Stacked tensors (dim=0):
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape of stacked tensors (dim=0): torch.Size([2, 2, 2])

Stacked tensors (dim=1):
 tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
Shape of stacked tensors (dim=1): torch.Size([2, 2, 2])

Concatenated tensors (dim=0):
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Shape of concatenated tensors (dim=0): torch.Size([4, 2])

Concatenated tensors (dim=1):
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Shape of concatenated tensors (dim=1): torch.Size([2, 4])


### Squeezing a tensor (removing an extra dimension)

In [ ]:
tensor_with_extra_dim = torch.randn(1, 3, 1, 4)
print("Original tensor with extra dimensions:\n", tensor_with_extra_dim)
print("Original shape:", tensor_with_extra_dim.shape)

# Squeeze all dimensions of size 1
squeezed_tensor = tensor_with_extra_dim.squeeze()
print("\nSqueezed tensor (all dimensions of size 1 removed):\n", squeezed_tensor)
print("Squeezed shape:", squeezed_tensor.shape)

# Squeeze a specific dimension of size 1 (e.g., dim=2, which is the 3rd dimension)
squeezed_specific_dim = tensor_with_extra_dim.squeeze(2)
print("\nSqueezed tensor (dim=2 removed):\n", squeezed_specific_dim)
print("Squeezed shape:", squeezed_specific_dim.shape)

Original tensor with extra dimensions:
 tensor([[[[-4.3347e-02, -5.6397e-04, -1.0751e+00,  2.3081e+00]],

         [[ 2.3635e-01,  1.5632e+00,  1.2026e+00,  1.9042e+00]],

         [[-1.6564e+00,  5.4169e-01,  4.9887e-01,  7.0598e-01]]]])
Original shape: torch.Size([1, 3, 1, 4])

Squeezed tensor (all dimensions of size 1 removed):
 tensor([[-4.3347e-02, -5.6397e-04, -1.0751e+00,  2.3081e+00],
        [ 2.3635e-01,  1.5632e+00,  1.2026e+00,  1.9042e+00],
        [-1.6564e+00,  5.4169e-01,  4.9887e-01,  7.0598e-01]])
Squeezed shape: torch.Size([3, 4])

Squeezed tensor (dim=2 removed):
 tensor([[[-4.3347e-02, -5.6397e-04, -1.0751e+00,  2.3081e+00],
         [ 2.3635e-01,  1.5632e+00,  1.2026e+00,  1.9042e+00],
         [-1.6564e+00,  5.4169e-01,  4.9887e-01,  7.0598e-01]]])
Squeezed shape: torch.Size([1, 3, 4])


### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
original_tensor = torch.tensor([1, 2, 3, 4, 5, 6])
print("Original tensor:", original_tensor)
print("Original shape:", original_tensor.shape)

# Unsqueeze at dimension 0 (adds a new first dimension)
unsqueeze_dim0 = original_tensor.unsqueeze(0)
print("\nUnsqueeze (dim=0):", unsqueeze_dim0)
print("Shape after unsqueeze(0):", unsqueeze_dim0.shape)

# Unsqueeze at dimension 1 (adds a new second dimension)
unsqueeze_dim1 = original_tensor.unsqueeze(1)
print("\nUnsqueeze (dim=1):", unsqueeze_dim1)
print("Shape after unsqueeze(1):", unsqueeze_dim1.shape)

# Example with a 2D tensor
two_d_tensor = torch.tensor([[10, 20], [30, 40]])
print("\nOriginal 2D tensor:\n", two_d_tensor)
print("Shape of 2D tensor:", two_d_tensor.shape)

# Unsqueeze a 2D tensor at dimension 0
unsqueeze_2d_dim0 = two_d_tensor.unsqueeze(0)
print("\nUnsqueeze 2D (dim=0):\n", unsqueeze_2d_dim0)
print("Shape after unsqueeze(0):", unsqueeze_2d_dim0.shape)

# Unsqueeze a 2D tensor at dimension 1
unsqueeze_2d_dim1 = two_d_tensor.unsqueeze(1)
print("\nUnsqueeze 2D (dim=1):\n", unsqueeze_2d_dim1)
print("Shape after unsqueeze(1):", unsqueeze_2d_dim1.shape)

# Unsqueeze a 2D tensor at dimension 2
unsqueeze_2d_dim2 = two_d_tensor.unsqueeze(2)
print("\nUnsqueeze 2D (dim=2):\n", unsqueeze_2d_dim2)
print("Shape after unsqueeze(2):", unsqueeze_2d_dim2.shape)

Original tensor: tensor([1, 2, 3, 4, 5, 6])
Original shape: torch.Size([6])

Unsqueeze (dim=0): tensor([[1, 2, 3, 4, 5, 6]])
Shape after unsqueeze(0): torch.Size([1, 6])

Unsqueeze (dim=1): tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
Shape after unsqueeze(1): torch.Size([6, 1])

Original 2D tensor:
 tensor([[10, 20],
        [30, 40]])
Shape of 2D tensor: torch.Size([2, 2])

Unsqueeze 2D (dim=0):
 tensor([[[10, 20],
         [30, 40]]])
Shape after unsqueeze(0): torch.Size([1, 2, 2])

Unsqueeze 2D (dim=1):
 tensor([[[10, 20]],

        [[30, 40]]])
Shape after unsqueeze(1): torch.Size([2, 1, 2])

Unsqueeze 2D (dim=2):
 tensor([[[10],
         [20]],

        [[30],
         [40]]])
Shape after unsqueeze(2): torch.Size([2, 2, 1])


## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


**1**

In [ ]:
X = torch.randn(200, 7)
print(f"X shape: {X.shape}")

b = torch.randn(8, 1)
print(f"b shape: {b.shape}")

e = torch.randn(200, 1)
print(f"e shape: {e.shape}")

X shape: torch.Size([200, 7])
b shape: torch.Size([8, 1])
e shape: torch.Size([200, 1])


**2**

In [ ]:
ones_tensor = torch.ones(200, 1)
print(f"ones_tensor shape: {ones_tensor.shape}")

ones_tensor shape: torch.Size([200, 1])


**3**

In [ ]:
X = torch.cat((ones_tensor, X), dim=1)
print(f"Modified X shape: {X.shape}")
print(X.shape)

Modified X shape: torch.Size([200, 9])
torch.Size([200, 9])


**4**

In [ ]:
# Re-initialize tensors to ensure correct shapes
X_original = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)
ones_tensor = torch.ones(200, 1)

# Modify X by adding the tensor of ones as the first column
X = torch.cat((ones_tensor, X_original), dim=1)

# Compute y using the formula: y = Xb + e
y = X @ b + e
print(f"y shape: {y.shape}")

y shape: torch.Size([200, 1])


**5**

In [ ]:
X_transpose = X.T
b_hat = torch.inverse(X_transpose @ X) @ X_transpose @ y
print(f"b_hat shape: {b_hat.shape}")

b_hat shape: torch.Size([8, 1])


**6**

In [ ]:
y_hat = X @ b_hat
print(f"y_hat shape: {y_hat.shape}")

y_hat shape: torch.Size([200, 1])


**7**

In [ ]:
y_numpy = y.numpy()
y_hat_numpy = y_hat.numpy()

# Calculate MSE
mse = ((y_numpy - y_hat_numpy)**2).mean()

print(f"y (Numpy array) shape: {y_numpy.shape}")
print(f"y_hat (Numpy array) shape: {y_hat_numpy.shape}")
print(f"Mean Squared Error (MSE): {mse:.4f}")

y (Numpy array) shape: (200, 1)
y_hat (Numpy array) shape: (200, 1)
Mean Squared Error (MSE): 0.9322
